heart_attack:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: heart-attack-dataset
      dataset: heart_attack_dataset
      location: us-central1
      threads: 1
      keyfile: /home/josh/heart-attack-prediction/service-account-key/heart-attack-dataset-35065960d254.json
